apiVersion: v1
kind: Service
metadata:
  name: foodcart
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: foodcart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcart
spec:
  selector:
    matchLabels:
      app: foodcart
  template:
    metadata:
      labels:
        app: foodcart
    spec:
      containers:
      - name: foodcart
        image: nwillc/foodcart
        ports:
          - containerPort: 8080
